export const ADD_MOCARELLO = 'ADD_MOCARELLO'
export const REMOVE_MOCARELLO = 'REMOVE_MOCARELLO'

export const ADD_TARTUFATA = 'ADD_TARTUFATA'
export const REMOVE_TARTUFATA = 'REMOVE_TARTUFATA'

export const ADD_MARGHARITA = 'ADD_MARGHARITA'
export const REMOVE_MARGHARITA = 'REMOVE_MARGHARITA'

export const ADD_ITALIAN = 'ADD_ITALIAN'
export const REMOVE_ITALIAN = 'REMOVE_ITALIAN'

export const ADD_COCABELLA = 'ADD_COCABELLA'
export const REMOVE_COCABELLA = 'REMOVE_COCABELLA'

export const ADD_TWENKY = 'ADD_TWENKY'
export const REMOVE_TWENKY = 'REMOVE_TWENKY'

export const ADD_KESTERATA = 'ADD_KESTERATA'
export const REMOVE_KESTERATA = 'REMOVE_KESTERATA'

export const ADD_NAMELITA = 'ADD_NAMELITA'
export const REMOVE_NAMELITA = 'REMOVE_NAMELITA'

export const ADD_TO_CART = 'ADD_TO_CART'